### ISSUE TITLE
Validating params?

### ISSUE THREAD

**Issue by kokujin** [trainiac/express-jsonschema#7]
Given an API route:

```
router.get('/users/:id', function(req, res, next) {
  res.send('respond with a resource');
});
```

How would I write the schema to validate req.params.id? The docs only show the lib validating the body. Thanks

**Comment by reecefenwick** [comment]
You can include regex patterns in your route, which is supported in express itself.

Refer to this stackoverflow http://stackoverflow.com/questions/11258442/express-routes-parameter-conditions

**Comment by trainiac** [comment]
There are a few ways to handle this error but I actually think it's best to handle the error with in the get handler function.  If the client asks for a user id that doesn't exist, you probably want to return a 404 with a custom message like, "Sorry, userID "XYZ" not found".  You don't want to return something like "id is not a string", "id is not a number", or "id is not a valid id" because this exposes implementation details about your application.  It's a yucky response to give and it leaks information that can compromise the security of your application.
